### ISSUE TITLE
false positive when variable is used on right side of assignment

### ISSUE THREAD

**Issue by stefanandres** [deanwilson/puppet-lint_duplicate_class_parameters-check#8]
puppet-lint throws a warning even though the parameter $foo is not assigned multiple times.

```
$ cat foo.pp
#
class foo (
  $foo = 'bar',
  $moo = $foo,
) {
  fail()
}
$ puppet-lint foo.pp

WARNING: found duplicate parameter 'foo' in class 'foo' on line 4
$
```

**Comment by stefanandres** [comment]
Also stuff like this triggers it:
```
  Boolean           $nagios_innodb_enable             = $sys11mysql::params::production_environment,
  Boolean           $nagios_myisam_enable             = $sys11mysql::params::production_environment,
  Boolean           $nagios_max_memory_usage_enable   = $sys11mysql::params::production_environment,
```

**Comment by deanwilson** [comment]
Hi @stefanandres 
  Apologies for the delay in getting to this, seems i'm not getting alerted on issues. Would you be able to test #9 please and see if that addresses your issues?

Thank you for raising the original issue.

  Dean

**Comment by stefanandres** [comment]
Hey, greatly appreciate your fix. It indeed fixes both issues.

**Comment by deanwilson** [comment]
I've merged #9 in and pushed a new version to rubygems. Thank you for finding the issue, and testing the fix.

**Comment by stefanandres** [comment]
I have to thank you for writing the gem :)

**Comment by cbeneke** [comment]
unfortunately the problem still occurs, when the variable is just a substring of another variable. Example:

```
$ cat foo.pp
class foo (
  $foo = 'bar',
  $moo = "foo ${foo}",
) {
  fail()
}
$ puppet-lint foo.pp

WARNING: found duplicate parameter 'foo' in class 'foo' on line 4
```

**Comment by deanwilson** [comment]
I think this is fixed in #10 - can you confirm @sattelite

**Comment by cbeneke** [comment]
Hello @deanwilson , sorry for the long response time. #10 fixes the problem. Thanks!

**Comment by deanwilson** [comment]
Many thanks for reporting the issue @sattelite, and for testing the fix.

`Successfully registered gem: puppet-lint-duplicate_class_parameters-check (1.0.4)`

So you should be able to use the gem as normal again.

**Comment by baurmatt** [comment]
Hey @deanwilson, sorry this seem still to happen :(

```bash
mbaur(2018-03-16 16:12:11)  /tmp/test/manifests
$ gem list puppet-lint-duplicate_class_parameters-check

*** LOCAL GEMS ***


mbaur(2018-03-16 16:12:12)  /tmp/test/manifests
$ puppet-lint init.pp
mbaur(2018-03-16 16:12:15)  /tmp/test/manifests
$ gem install puppet-lint-duplicate_class_parameters-check
Fetching: puppet-lint-duplicate_class_parameters-check-1.0.4.gem (100%)
Successfully installed puppet-lint-duplicate_class_parameters-check-1.0.4
1 gem installed
mbaur(2018-03-16 16:12:21)  /tmp/test/manifests
$ puppet-lint init.pp
init.pp - WARNING: found duplicate parameter '::vlan' in class 'test' on line 4
mbaur(2018-03-16 16:12:24)  /tmp/test/manifests
$ cat init.pp
#
class test (
  Array[String]           $export_tags = [ "vlan${::vlan}", ],
  Array[String]           $import_tags = [ "vlan${::vlan}", 'backupserver', ],
) {
}
```
